# Generated by Django 5.0.4 on 2024-04-24 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleInterview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(default='confirmation pending', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255)),
                ('question1', models.TextField()),
                ('demo_answer1', models.TextField()),
                ('question2', models.TextField()),
                ('demo_answer2', models.TextField()),
                ('question3', models.TextField()),
                ('demo_answer3', models.TextField()),
                ('question4', models.TextField()),
                ('demo_answer4', models.TextField()),
                ('question5', models.TextField()),
                ('demo_answer5', models.TextField()),
                ('question6', models.TextField()),
                ('demo_answer6', models.TextField()),
                ('question7', models.TextField()),
                ('demo_answer7', models.TextField()),
                ('question8', models.TextField()),
                ('demo_answer8', models.TextField()),
                ('question9', models.TextField()),
                ('demo_answer9', models.TextField()),
                ('question10', models.TextField()),
                ('demo_answer10', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnsweredSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255)),
                ('question1', models.TextField()),
                ('user_answer1', models.TextField(blank=True, null=True)),
                ('question2', models.TextField()),
                ('user_answer2', models.TextField(blank=True, null=True)),
                ('question3', models.TextField()),
                ('user_answer3', models.TextField(blank=True, null=True)),
                ('question4', models.TextField()),
                ('user_answer4', models.TextField(blank=True, null=True)),
                ('question5', models.TextField()),
                ('user_answer5', models.TextField(blank=True, null=True)),
                ('question6', models.TextField()),
                ('user_answer6', models.TextField(blank=True, null=True)),
                ('question7', models.TextField()),
                ('user_answer7', models.TextField(blank=True, null=True)),
                ('question8', models.TextField()),
                ('user_answer8', models.TextField(blank=True, null=True)),
                ('question9', models.TextField()),
                ('user_answer9', models.TextField(blank=True, null=True)),
                ('question10', models.TextField()),
                ('user_answer10', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.session')),
            ],
        ),
    ]
